experimental-features = nix-command flakes local-overlay-store read-only-local-store
store = local-overlay://?root=/&lower-store=local%3Froot%3D%2Fmnt%2Framdisk%2Fprivate%2Fmodels%2Fnix%26read-only%3Dtrue&upper-layer=/nix/store.upper&check-mount=false
flake-registry = /nix/var/nix/profiles/default/etc/nix/registry.json
build-users-group =
sandbox = false
substituters = https://cache.nixos.org
